# Generated by Django 2.2.16 on 2022-07-10 01:48

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220710_0118'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='restricted_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='restricted_multifollow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='restricted_self_follow'),
        ),
    ]
